### ISSUE TITLE
miss file "input.csv"

### ISSUE THREAD

**Issue by wl3b10s** [ppplinday/vgg16-by-ARM-Compute-Library#2]
do you forget to include your test input file?

when i try to run your project, i find that there is no input.csv in the folder.

thanks.

**Comment by ppplinday** [comment]
Hi:
Sorry about that, I forgot to upload the input.csv buscause the input.csv can be made by yourself, it is a picture(224, 224, 3) information.
For convenience，you can create a input.csv with 224 * 224 * 3 number of zero to test the main.cpp.

Feel free to ask me if you have any questions and thanks for your feedback!!!

**Comment by wl3b10s** [comment]
thanks. i make a sample csv and it run on my phone. 
take about time: 74596671 us.
but there is no /data/local/tmp/synset.txt 
and no error message ...

i  don't know what happened behind.

**Comment by wl3b10s** [comment]
i guess this synset.txt should be an output file and ready for read and cout.
but i don't know its inexistence  is because of the abnormal of exection or some missing code?
thanks

**Comment by ppplinday** [comment]
Hi:

synset.txt is a label file, you can download it in google vgg.
I forgot to upload it to the github and sorry about that!

Thanks for your feedback!

**Comment by wl3b10s** [comment]
thanks very much.
 i test a car pic , it works fine but the possibility is low as 0.005. but when input other pic , can't get the correct result. and always the result as the first pic.
maybe the sth need to be modified beside the input.csv?  i think...

always like this:
N0 1 0.00486922 is n03777568 Model T
N0 2 0.0041888 is n01847000 drake
N0 3 0.00310822 is n01729977 green snake, grass snake
N0 4 0.00295665 is n01667114 mud turtle
N0 5 0.0026507 is n03062245 cocktail shaker

**Comment by ppplinday** [comment]
Hi:

The purpose of this program is to test the performance that run the vgg in the Android phone with ARM Compute Library. And I remembered that some results of this network were wrong.
I think some problem is about my weight. The number of weight is right I checked before, but the order may be wrong I think. For example, the weight like this way:
[1,2,3]
[4,5,6]
[7,8,9]
It means there are three points and the first point`s RGB is [1,4,7], the second is [2,5,8] and the final is [7,8,9].
However, in my program, I think I upload the weight without the right order.
Perhaps I upload the weight like: the first is [1,2,3], the second[4,5,6]and the finak[7,8,9].
I think this is reason why it cannot work well. I ddi not modify it because I only want to run it and see its performance.

Thanks for your feedback and you can try to modify the upload function which I think it is very easy to do that and feel free to ask again if you have other question!!!Thanks for you feedback again!!!

**Comment by wl3b10s** [comment]
the last question, whether it should function as your project "tensorflow-vgg16-train-and-test" that can only recognize cat and dog?

**Comment by ppplinday** [comment]
Hi:

It`s function is different to "tensorflow-vgg16-train-and-test", it is normal vgg16 network which can recognize 1000 style picture
